/*
 * !!!!! DO NOT EDIT THIS FILE !!!!!
 *
 * This file was generated from
 *   dictionary/structure/v4/content/sparse_table_dict_content.cpp
 */

#include "dictionary/structure/backward/v402/content/sparse_table_dict_content.h"

namespace latinime {
namespace backward {
namespace v402 {

bool SparseTableDictContent::flush(const char *const dictPath,
        const char *const lookupTableFileNameSuffix, const char *const addressTableFileNameSuffix,
        const char *const contentFileNameSuffix) const {
    if (!DictFileWritingUtils::flushBufferToFileWithSuffix(dictPath, lookupTableFileNameSuffix,
            &mExpandableLookupTableBuffer)){
        return false;
    }
    if (!DictFileWritingUtils::flushBufferToFileWithSuffix(dictPath, addressTableFileNameSuffix,
            &mExpandableAddressTableBuffer)) {
        return false;
    }
    if (!DictFileWritingUtils::flushBufferToFileWithSuffix(dictPath, contentFileNameSuffix,
            &mExpandableContentBuffer)) {
        return false;
    }
    return true;
}

} // namespace v402
} // namespace backward
} // namespace latinime
